In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\AKSHAT\Desktop\E-Com Project\messy_ecommerce_sales_data.csv")

pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)



df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,Basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,Blender,electronic,-2,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,Yoga Mat,ELECTRONICS,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,Vacuum,electronic,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,Lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,Yoga Mat,ELECTRONICS,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,T-shirt,Clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,Smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,Vacuum,Home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,T-shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,Tennis Racket,Sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,T-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,Basketball,Sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,Microwave,ELECTRONICS,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,Jacket,Clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,Home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [4]:
df.shape

(103, 11)

In [5]:
df.columns

Index(['ID', ' Customer_Name', 'Order_ID', 'Order_Date', 'Product',
       ' Category', 'Quantity', 'Price', 'Payment_Method', 'Status', 'Total'],
      dtype='object')

In [6]:
df.dtypes

ID                  int64
 Customer_Name     object
Order_ID           object
Order_Date         object
Product            object
 Category          object
Quantity           object
Price              object
Payment_Method     object
Status             object
Total             float64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    object
 2   Order_ID        103 non-null    object
 3   Order_Date      103 non-null    object
 4   Product         103 non-null    object
 5    Category       95 non-null     object
 6   Quantity        98 non-null     object
 7   Price           98 non-null     object
 8   Payment_Method  103 non-null    object
 9   Status          103 non-null    object
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), object(9)
memory usage: 9.0+ KB

In [8]:
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [9]:
# cleaning Column Names 
df.columns = df.columns.str.strip()
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,Basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,Blender,electronic,-2,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,Yoga Mat,ELECTRONICS,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,Vacuum,electronic,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,Lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,Yoga Mat,ELECTRONICS,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,T-shirt,Clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,Smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,Vacuum,Home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,T-shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,Tennis Racket,Sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,T-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,Basketball,Sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,Microwave,ELECTRONICS,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,Jacket,Clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,Home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [10]:
# Stripping Extra Spaces from The Category Column
df["Category"] = df["Category"].str.strip() 
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,Basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,Blender,electronic,-2,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,Yoga Mat,ELECTRONICS,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,Vacuum,electronic,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,Lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,Yoga Mat,ELECTRONICS,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,T-shirt,Clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,Smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,Vacuum,Home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,T-shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,Tennis Racket,Sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,T-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,Basketball,Sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,Microwave,ELECTRONICS,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,Jacket,Clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,Home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [11]:
#Keeping All Letter to Lowercase
df["Category"] = df["Category"].str.lower()
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,Tennis Racket,sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,Blender,home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,Biography,books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,Science,books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,Tennis Racket,sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,Basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,Comics,books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,Shoes,clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,Fiction,books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,Smartphone,electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,Fiction,books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,Microwave,home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,Blender,electronic,-2,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,Science,books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,Basketball,sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,Yoga Mat,electronics,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,Basketball,sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,Microwave,home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,Vacuum,electronic,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,Comics,books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,Comics,books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,Shoes,clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,Blender,home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,Lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,Science,books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,Tennis Racket,sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,Lamp,home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,Yoga Mat,electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,T-shirt,clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,Smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,Vacuum,home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,Lamp,home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,Smartphone,electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,Fiction,books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,Fiction,books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,Shoes,clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,T-shirt,clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,Football,sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,Laptop,electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,Jacket,clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,Tennis Racket,sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,Comics,books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,Yoga Mat,sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,Comics,books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,Lamp,home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,Yoga Mat,sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,Blender,home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,Jeans,clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,Jacket,clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,Smartwatch,electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,Microwave,home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,Science,books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,Science,books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,Blender,home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,Smartwatch,electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,Tennis Racket,sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,Shoes,clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,T-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,Basketball,sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,Biography,books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,Basketball,sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,Jeans,clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,Shoes,clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,Comics,books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,Lamp,home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,Microwave,electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,Headphones,electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,Comics,books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,Laptop,electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,Tennis Racket,sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,Yoga Mat,sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,Shoes,clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,Football,sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,Laptop,electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,Smartphone,electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,Microwave,home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,Lamp,home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,Vacuum,home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,Fiction,books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,Jacket,clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,Lamp,home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,Biography,books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,Blender,home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [12]:
df["Product"] = df["Product"].str.strip()
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,Tennis Racket,sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,Blender,home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,Biography,books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,Science,books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,Tennis Racket,sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,Basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,Comics,books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,Shoes,clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,Fiction,books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,Smartphone,electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,Fiction,books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,Microwave,home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,Blender,electronic,-2,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,Science,books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,Basketball,sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,Yoga Mat,electronics,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,Basketball,sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,Microwave,home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,Vacuum,electronic,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,Comics,books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,Comics,books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,Shoes,clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,Blender,home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,Lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,Science,books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,Tennis Racket,sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,Lamp,home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,Yoga Mat,electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,T-shirt,clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,Smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,Vacuum,home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,Lamp,home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,Smartphone,electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,Fiction,books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,Fiction,books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,Shoes,clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,T-shirt,clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,Football,sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,Laptop,electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,Jacket,clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,Tennis Racket,sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,Comics,books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,Yoga Mat,sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,Comics,books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,Lamp,home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,Yoga Mat,sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,Blender,home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,Jeans,clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,Jacket,clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,Smartwatch,electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,Microwave,home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,Science,books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,Science,books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,Blender,home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,Smartwatch,electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,Tennis Racket,sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,Shoes,clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,T-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,Basketball,sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,Biography,books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,Basketball,sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,Jeans,clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,Shoes,clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,Comics,books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,Lamp,home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,Microwave,electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,Headphones,electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,Comics,books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,Laptop,electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,Tennis Racket,sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,Yoga Mat,sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,Shoes,clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,Football,sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,Laptop,electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,Smartphone,electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,Microwave,home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,Lamp,home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,Vacuum,home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,Fiction,books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,Jacket,clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,Lamp,home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,Biography,books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,Blender,home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [13]:
df["Product"] = df["Product"].str.lower()
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronic,-2,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronic,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [14]:
df["Category"]= df["Category"].replace("electronic", "electronics")
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,-2,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840

In [15]:
df["Category"].unique()

array(['home', 'electronics', 'sports', 'books', 'clothing', nan],
      dtype=object)

In [16]:
df.isnull().sum()

ID                 0
Customer_Name      0
Order_ID           0
Order_Date         0
Product            0
Category           8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [17]:
df["Quantity"].unique()

array(['3', '2', '1', '5', nan, '4', '-2', '-5', '4a'], dtype=object)

In [18]:
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,-2,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840

In [19]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3.0,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2.0,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1.0,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5.0,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1.0,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3.0,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5.0,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1.0,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5.0,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5.0,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2.0,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4.0,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1.0,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2.0,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2.0,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4.0,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,-2.0,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5.0,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4.0,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5.0,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4.0,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2.0,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3.0,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5.0,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4.0,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4.0,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5.0,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3.0,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4.0,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2.0,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5.0,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1.0,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5.0,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,-5.0,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4.0,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1.0,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3.0,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1.0,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2.0,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4.0,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3.0,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5.0,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5.0,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5.0,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2.0,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2.0,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4.0,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1.0,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5.0,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1.0,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2.0,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3.0,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4.0,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5.0,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1.0,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2.0,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4.0,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1.0,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3.0,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5.0,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4.0,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2.0,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3.0,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2.0,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2.0,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2.0,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1.0,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5.0,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3.0,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2.0,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5.0,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4.0,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1.0,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5.0,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1.0,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3.0,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3.0,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2.0,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1.0,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4.0,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5.0,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4.0,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2.0,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1.0,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3.0,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5.0,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1.0,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1.0,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2.0,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,NaN,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5.0,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5.0,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1.0,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2.0,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5.0,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1.0,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5.0,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2.0,705.42,Bank Transfer,Processing,1410.840

In [20]:
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3.0,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2.0,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1.0,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5.0,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1.0,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3.0,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5.0,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1.0,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5.0,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5.0,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2.0,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4.0,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1.0,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2.0,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2.0,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4.0,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,-2.0,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5.0,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4.0,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5.0,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4.0,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2.0,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3.0,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5.0,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4.0,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4.0,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5.0,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3.0,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4.0,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2.0,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5.0,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1.0,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5.0,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,-5.0,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4.0,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1.0,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3.0,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1.0,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2.0,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4.0,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3.0,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5.0,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5.0,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5.0,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2.0,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2.0,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4.0,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1.0,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5.0,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1.0,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2.0,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3.0,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4.0,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5.0,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1.0,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2.0,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4.0,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1.0,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3.0,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5.0,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4.0,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2.0,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3.0,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2.0,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2.0,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2.0,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1.0,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5.0,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3.0,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2.0,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5.0,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4.0,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1.0,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5.0,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1.0,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3.0,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3.0,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2.0,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1.0,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4.0,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5.0,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4.0,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2.0,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1.0,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3.0,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5.0,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1.0,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1.0,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2.0,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,NaN,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5.0,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5.0,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1.0,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2.0,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5.0,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1.0,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5.0,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2.0,705.42,Bank Transfer,Processing,1410.840

In [21]:
df[df["Quantity"]<0]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,-2.0,10000,Cash on Delivery,Processing,-20000.00
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,-5.0,591.53,PayPal,Shipped,-2957.65

In [22]:
df.loc[df["Quantity"]<0, "Quantity"]= np.nan
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3.0,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2.0,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1.0,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5.0,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1.0,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3.0,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5.0,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1.0,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5.0,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5.0,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2.0,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4.0,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1.0,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2.0,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2.0,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4.0,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,NaN,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5.0,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4.0,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5.0,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4.0,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2.0,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3.0,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5.0,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4.0,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4.0,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5.0,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3.0,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4.0,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2.0,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5.0,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1.0,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5.0,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,NaN,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4.0,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1.0,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3.0,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1.0,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2.0,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4.0,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3.0,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5.0,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5.0,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5.0,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2.0,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2.0,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4.0,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1.0,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5.0,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1.0,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2.0,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3.0,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4.0,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5.0,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1.0,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2.0,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4.0,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1.0,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3.0,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5.0,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4.0,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2.0,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3.0,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2.0,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2.0,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2.0,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1.0,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5.0,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3.0,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2.0,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5.0,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4.0,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1.0,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5.0,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1.0,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3.0,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3.0,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2.0,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1.0,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4.0,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5.0,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4.0,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2.0,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1.0,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3.0,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5.0,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1.0,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1.0,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2.0,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,NaN,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5.0,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5.0,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1.0,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2.0,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5.0,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1.0,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5.0,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2.0,705.42,Bank Transfer,Processing,1410.840

In [23]:
df["Quantity"].unique()

array([ 3.,  2.,  1.,  5., nan,  4.])

In [24]:
df["Quantity"]= df["Quantity"].fillna(df["Quantity"].median())
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3.0,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2.0,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1.0,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5.0,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1.0,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3.0,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,3.0,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5.0,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1.0,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5.0,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5.0,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2.0,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4.0,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1.0,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2.0,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2.0,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4.0,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,3.0,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5.0,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4.0,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5.0,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4.0,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2.0,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3.0,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5.0,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4.0,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4.0,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5.0,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3.0,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4.0,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2.0,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5.0,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1.0,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5.0,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,3.0,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4.0,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1.0,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3.0,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1.0,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2.0,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4.0,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3.0,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5.0,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5.0,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5.0,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2.0,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2.0,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4.0,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1.0,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5.0,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1.0,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2.0,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3.0,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4.0,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5.0,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1.0,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2.0,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4.0,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1.0,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3.0,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5.0,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4.0,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2.0,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3.0,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,3.0,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2.0,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2.0,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,3.0,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2.0,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1.0,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5.0,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3.0,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2.0,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5.0,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4.0,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1.0,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5.0,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1.0,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3.0,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3.0,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2.0,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1.0,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4.0,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5.0,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4.0,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2.0,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1.0,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3.0,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5.0,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1.0,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1.0,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2.0,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,3.0,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,3.0,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5.0,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5.0,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,3.0,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1.0,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2.0,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5.0,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1.0,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5.0,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2.0,705.42,Bank Transfer,Processing,1410.840

In [25]:
df["Quantity"] = df["Quantity"].round().astype(int)
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,3,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,3,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,3,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,3,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,3,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,3,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,3,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,3,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840

In [26]:
df["Price"] = df["Price"].astype(str).str.strip()

In [27]:
df["Price"].unique()

array(['38', 'abd', '389.05', '233.92', '552.51', '122.06', '978.63',
       '587.68', '600.29', '168.34', 'four hundred', '865.77', '752.13',
       '411.81', '413.13', '796.84', 'nan', '10000', '247.82', '438.19',
       '300$', '523.01', '556.93', '615.91', '765.69', '836.8', '336.02',
       '898.69', '736.71', '616.63', '266.7', '343.24', '591.53',
       '446.19', '696.71', '-100', '531.06', '681.38', '588.98', '546.04',
       '645.26', '826.77', '849.07', '860.99', '705.42', '596.15',
       '660.98', '896.38', '206.19', '457.16', '233.11', '278.9',
       '789.64', '40.95', '275.1', '933.58', '163.16', '242.52', '209.32',
       '155.76', '235.26', '587.64', '443.13', '569.38', '593.93',
       '141.49', '582.13', '741.63', '688.68', '942.76', '351.89',
       '187.48', '111.36', '530.52', '69.48', '472.14', '868.67',
       '418.38', '266.48', '538.35', '101.19', '730.92', '365.34',
       '882.96', '504.05', '814.68', '920.37', '881.02', '203.63',
       '522.02', '944.54', '817.46', '160.16', '497.01', '372.28'],
      dtype=object)

In [28]:
df["Price"] = df["Price"].str.replace('$','',regex=False)
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,3,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4,nan,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,3,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5,300,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5,nan,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2,nan,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,3,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2,nan,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,3,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,3,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5,nan,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,3,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,3,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,3,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840

In [29]:
df["Price"]= pd.to_numeric(df["Price"],errors="coerce")
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3,38.00,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,3,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5,NaN,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,3,10000.00,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5,300.00,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4,836.80,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1,266.70,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,3,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3,-100.00,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4,278.90,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4,275.10,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,3,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,3,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,3,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,3,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,3,NaN,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840

In [30]:
df.loc[df["Price"] <= 0, "Price"] = np.nan
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3,38.00,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,3,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5,NaN,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,3,10000.00,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5,300.00,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4,836.80,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1,266.70,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,3,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3,NaN,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4,278.90,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4,275.10,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,3,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,3,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,3,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,3,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,3,NaN,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.42,Bank Transfer,Processing,1410.840

In [31]:
df["Price"] = df["Price"].fillna(df["Price"].median())
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,blender,home,3,38.000,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,smartphone,electronics,2,542.195,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,tennis racket,sports,1,389.050,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,science,books,5,233.920,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,biography,books,1,552.510,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,tennis racket,sports,3,122.060,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,blender,home,3,978.630,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,biography,books,5,587.680,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,science,books,1,600.290,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,tennis racket,sports,5,168.340,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,basketball,sports,5,542.195,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,comics,books,2,865.770,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,shoes,clothing,4,752.130,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,fiction,books,1,411.810,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,smartphone,electronics,2,413.130,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,fiction,books,2,796.840,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,microwave,home,4,542.195,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,blender,electronics,3,10000.000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,science,books,5,247.820,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,basketball,sports,4,438.190,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,yoga mat,electronics,5,300.000,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,basketball,sports,4,523.010,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,microwave,home,2,556.930,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,vacuum,electronics,3,615.910,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,comics,books,5,542.195,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,comics,books,4,765.690,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,shoes,clothing,4,836.800,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,blender,home,5,336.020,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,lamp,electronics,3,898.690,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,science,books,4,736.710,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,tennis racket,sports,2,542.195,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,lamp,home,5,616.630,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,yoga mat,electronics,1,266.700,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,biography,NaN,5,343.240,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,t-shirt,clothing,3,591.530,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,smartwatch,electronics,4,446.190,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,headphones,NaN,1,696.710,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,vacuum,home,3,542.195,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,lamp,home,1,531.060,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,smartphone,electronics,2,681.380,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,fiction,books,4,588.980,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,fiction,books,3,546.040,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.260,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,t-shirt,clothing,5,826.770,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,football,sports,5,849.070,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,laptop,electronics,2,860.990,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.420,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,jacket,clothing,4,596.150,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,tennis racket,sports,1,660.980,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,comics,books,5,896.380,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,yoga mat,sports,1,206.190,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,comics,books,2,457.160,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,lamp,home,3,233.110,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,yoga mat,sports,4,278.900,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,blender,home,5,789.640,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,clothing,1,40.950,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,jeans,clothing,2,542.195,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,jacket,clothing,4,275.100,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,smartwatch,electronics,1,933.580,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,microwave,home,3,163.160,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,science,books,5,242.520,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,science,books,4,209.320,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,blender,home,2,155.760,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,smartwatch,electronics,3,235.260,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,tennis racket,sports,3,587.640,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,shoes,clothing,2,443.130,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,t-shirt,electronics,2,569.380,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,basketball,sports,3,593.930,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,biography,books,2,141.490,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,basketball,sports,1,582.130,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,jeans,clothing,5,741.630,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,shoes,clothing,3,688.680,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,comics,books,2,942.760,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,lamp,home,5,351.890,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,microwave,electronics,4,187.480,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.360,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,comics,books,5,530.520,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,laptop,electronics,1,69.480,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,tennis racket,sports,3,472.140,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,yoga mat,sports,3,868.670,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,laptop,NaN,2,418.380,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,smartphone,NaN,1,266.480,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,shoes,NaN,4,538.350,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,shoes,clothing,5,542.195,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,jeans,NaN,4,101.190,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,football,sports,2,730.920,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,laptop,electronics,1,365.340,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,smartphone,electronics,3,882.960,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,microwave,home,5,504.050,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,lamp,home,1,814.680,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,vacuum,home,1,920.370,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,fiction,books,2,881.020,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,jacket,clothing,3,203.630,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,basketball,NaN,3,522.020,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,lamp,home,5,944.540,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,biography,books,5,817.460,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,vacuum,home,3,542.195,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,blender,home,1,160.160,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,vacuum,NaN,2,497.010,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,blender,home,5,372.280,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,headphones,electronics,1,111.360,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,shoes,clothing,5,645.260,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,basketball,electronics,2,705.420,Bank Transfer,Processing,1410.840

In [39]:
df["Order_Date"]= pd.to_datetime(df["Order_Date"],errors="coerce")

In [41]:
df[df["Order_Date"].isnull()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
14,114,Customer_114,ORD-77417,NaT,smartphone,electronics,2,413.13,Cash on Delivery,Shipped,826.26
92,192,Customer_192,ORD-35144,NaT,jacket,clothing,3,203.63,Credit Card,Returned,NaN

In [94]:
df = df.dropna(subset="Order_Date")

In [47]:
df2 = df.copy()
df2

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,blender,home,3,38.000,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,smartphone,electronics,2,542.195,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,tennis racket,sports,1,389.050,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,science,books,5,233.920,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,biography,books,1,552.510,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,2024-11-20,tennis racket,sports,3,122.060,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2025-02-02,blender,home,3,978.630,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,2025-01-03,biography,books,5,587.680,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,2025-10-23,science,books,1,600.290,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,2025-05-03,tennis racket,sports,5,168.340,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,2025-09-26,basketball,sports,5,542.195,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,2025-10-22,comics,books,2,865.770,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,2025-03-02,shoes,clothing,4,752.130,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,2025-07-24,fiction,books,1,411.810,Credit Card,Processing,411.810
15,115,Customer_115,ORD-72778,2025-01-10,fiction,books,2,796.840,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,2025-10-30,microwave,home,4,542.195,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2025-02-12,blender,electronics,3,10000.000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,2025-05-31,science,books,5,247.820,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,2024-12-19,basketball,sports,4,438.190,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,2025-06-13,yoga mat,electronics,5,300.000,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,2025-10-11,basketball,sports,4,523.010,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,2025-05-16,microwave,home,2,556.930,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,2025-10-06,vacuum,electronics,3,615.910,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,2025-05-31,comics,books,5,542.195,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2025-02-09,comics,books,4,765.690,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,2025-05-18,shoes,clothing,4,836.800,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,2025-05-12,blender,home,5,336.020,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,2024-11-10,lamp,electronics,3,898.690,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,2025-06-22,science,books,4,736.710,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,2025-08-15,tennis racket,sports,2,542.195,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,2025-06-11,lamp,home,5,616.630,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,2025-04-02,yoga mat,electronics,1,266.700,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,2024-12-05,biography,NaN,5,343.240,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,2025-10-04,t-shirt,clothing,3,591.530,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2025-02-09,smartwatch,electronics,4,446.190,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,2025-06-12,headphones,NaN,1,696.710,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2025-02-23,vacuum,home,3,542.195,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,2025-08-09,lamp,home,1,531.060,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2025-02-09,smartphone,electronics,2,681.380,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2025-02-26,fiction,books,4,588.980,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2025-02-13,fiction,books,3,546.040,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,2025-10-30,shoes,clothing,5,645.260,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,2025-07-11,t-shirt,clothing,5,826.770,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,2025-01-27,football,sports,5,849.070,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,2023-05-01,laptop,electronics,2,860.990,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,2025-07-09,basketball,electronics,2,705.420,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,2025-05-01,jacket,clothing,4,596.150,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,2025-03-13,tennis racket,sports,1,660.980,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,2025-06-29,comics,books,5,896.380,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,2024-11-27,yoga mat,sports,1,206.190,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,2025-07-01,comics,books,2,457.160,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,2025-09-22,lamp,home,3,233.110,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,2025-07-16,yoga mat,sports,4,278.900,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2025-02-21,blender,home,5,789.640,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,2025-05-01,shoes,clothing,1,40.950,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,2024-11-28,jeans,clothing,2,542.195,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,2025-11-06,jacket,clothing,4,275.100,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,2025-04-05,smartwatch,electronics,1,933.580,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,2025-07-28,microwave,home,3,163.160,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,2025-01-03,science,books,5,242.520,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,2024-12-15,science,books,4,209.320,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,2025-05-19,blender,home,2,155.760,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,2023-01-05,smartwatch,electronics,3,235.260,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2025-02-09,tennis racket,sports,3,587.640,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,2024-11-08,shoes,clothing,2,443.130,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,2025-07-03,t-shirt,electronics,2,569.380,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,2025-08-07,basketball,sports,3,593.930,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,2025-11-04,biography,books,2,141.490,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,2025-08-12,basketball,sports,1,582.130,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,2025-10-03,jeans,clothing,5,741.630,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,2024-12-06,shoes,clothing,3,688.680,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,2024-11-18,comics,books,2,942.760,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,2025-10-11,lamp,home,5,351.890,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,2025-09-20,microwave,electronics,4,187.480,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2025-02-24,headphones,electronics,1,111.360,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,2025-07-22,comics,books,5,530.520,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,2025-07-28,laptop,electronics,1,69.480,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,2025-09-18,tennis racket,sports,3,472.140,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,2025-09-03,yoga mat,sports,3,868.670,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,2025-03-26,laptop,NaN,2,418.380,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,2024-12-29,smartphone,NaN,1,266.480,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,2025-08-03,shoes,NaN,4,538.350,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,2025-03-10,shoes,clothing,5,542.195,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2025-02-15,jeans,NaN,4,101.190,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,2025-08-14,football,sports,2,730.920,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,2025-10-06,laptop,electronics,1,365.340,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,2024-11-19,smartphone,electronics,3,882.960,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,2024-11-19,microwave,home,5,504.050,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,2025-08-14,lamp,home,1,814.680,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,2025-06-29,vacuum,home,1,920.370,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,2025-07-18,fiction,books,2,881.020,Cash on Delivery,Returned,1762.040
93,193,Customer_193,ORD-42475,2025-06-06,basketball,NaN,3,522.020,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2025-02-10,lamp,home,5,944.540,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,2025-06-19,biography,books,5,817.460,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,2024-12-23,vacuum,home,3,542.195,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,2025-06-23,blender,home,1,160.160,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,2025-07-27,vacuum,NaN,2,497.010,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,2025-01-22,blender,home,5,372.280,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2025-02-24,headphones,electronics,1,111.360,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,2025-10-30,shoes,clothing,5,645.260,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,2025-07-09,basketball,electronics,2,705.420,Bank Transfer,Processing,1410.840

In [93]:
df2["Payment_Method"]= df2["Payment_Method"].str.strip()

In [50]:
df2["Status"]=df["Status"].str.strip()

In [51]:
df2["Product"] = df2["Product"].str.strip()

In [54]:
df2["Order_ID"] = df2["Order_ID"].astype(str).str.strip()

In [64]:
df2["Order_ID"].duplicated().sum()

np.int64(2)

In [65]:
df2["Order_ID"]=df2["Order_ID"].drop_duplicates()

In [92]:
df2["Total"] = df["Quantity"] * df2["Price"]

In [75]:
df2.groupby("Category")["Total"].sum()

Category
books          41068.08
clothing       32698.52
electronics    51920.53
home           33087.54
sports         25076.32
Name: Total, dtype: float64

In [76]:
df2["Total"] = df2["Total"].round(2)

In [78]:
df2.dtypes

ID                         int64
Customer_Name             object
Order_ID                  object
Order_Date        datetime64[ns]
Product                   object
Category                  object
Quantity                   int64
Price                    float64
Payment_Method            object
Status                    object
Total                    float64
dtype: object

In [79]:
df2.isnull().sum()

ID                0
Customer_Name     0
Order_ID          3
Order_Date        0
Product           0
Category          8
Quantity          0
Price             0
Payment_Method    0
Status            0
Total             0
dtype: int64

In [80]:
print("Negative quantities:", (df["Quantity"] < 0).sum())
print("Negative prices:", (df["Price"] < 0).sum())
print("Negative totals:", (df["Total"] < 0).sum())

Negative quantities: 0
Negative prices: 0
Negative totals: 0

In [88]:
product_category = {
    "Blender": "home",
    "Microwave": "home",
    "Lamp": "home",
    "vacuum": "home",
    "smartphone": "electronics",
    "Smartwatch": "electronics",
    "laptop": "electronics",
    "headphones": "electronics",
    "basketball": "sports",
    "Tennis Racket": "sports",
    "Yoga Mat": "sports",
    "Football": "sports",
    "biography": "books",
    "Science": "books",
    "Comics": "books",
    "Fiction": "books",
    "shoes": "clothing",
    "T-shirt": "clothing",
    "Jacket": "clothing",
    "Jeans": "clothing"
}

In [89]:
df2["Category"]= df2["Category"].fillna(df2["Product"].map(product_category))

# Final Cleaned Dataset

In [91]:
df2

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,blender,home,3,38.000,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,2025-07-05,smartphone,electronics,2,542.195,PayPal,Processing,1084.39
2,102,Customer_102,ORD-84355,2024-12-23,tennis racket,sports,1,389.050,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,2025-03-19,science,books,5,233.920,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,2025-10-20,biography,books,1,552.510,Cash on Delivery,Processing,552.51
5,105,Customer_105,ORD-22442,2024-11-20,tennis racket,sports,3,122.060,Cash on Delivery,Cancelled,366.18
6,106,Customer_106,ORD-25885,2025-02-02,blender,home,3,978.630,Bank Transfer,Processing,2935.89
7,107,Customer_107,ORD-89122,2025-01-03,biography,books,5,587.680,PayPal,Returned,2938.40
8,108,Customer_108,ORD-64400,2025-10-23,science,books,1,600.290,Cash on Delivery,Processing,600.29
9,109,Customer_109,ORD-18512,2025-05-03,tennis racket,sports,5,168.340,Credit Card,Shipped,841.70
10,110,Customer_110,ORD-61020,2025-09-26,basketball,sports,5,542.195,Cash on Delivery,Cancelled,2710.97
11,111,Customer_111,ORD-72349,2025-10-22,comics,books,2,865.770,Credit Card,Returned,1731.54
12,112,Customer_112,ORD-80867,2025-03-02,shoes,clothing,4,752.130,Bank Transfer,Delivered,3008.52
13,113,Customer_113,ORD-23994,2025-07-24,fiction,books,1,411.810,Credit Card,Processing,411.81
15,115,Customer_115,ORD-72778,2025-01-10,fiction,books,2,796.840,Cash on Delivery,Returned,1593.68
16,116,Customer_116,ORD-63660,2025-10-30,microwave,home,4,542.195,Cash on Delivery,Processing,2168.78
17,117,Customer_117,ORD-72751,2025-02-12,blender,electronics,3,10000.000,Cash on Delivery,Processing,30000.00
18,118,Customer_118,ORD-96061,2025-05-31,science,books,5,247.820,PayPal,Processing,1239.10
19,119,Customer_119,ORD-76016,2024-12-19,basketball,sports,4,438.190,Cash on Delivery,Processing,1752.76
20,120,Customer_120,ORD-14659,2025-06-13,yoga mat,electronics,5,300.000,Credit Card,Cancelled,1500.00
21,121,Customer_121,ORD-80067,2025-10-11,basketball,sports,4,523.010,Credit Card,Delivered,2092.04
22,122,Customer_122,ORD-21443,2025-05-16,microwave,home,2,556.930,PayPal,Shipped,1113.86
23,123,Customer_123,ORD-11314,2025-10-06,vacuum,electronics,3,615.910,Cash on Delivery,Cancelled,1847.73
24,124,Customer_124,ORD-46136,2025-05-31,comics,books,5,542.195,PayPal,Cancelled,2710.97
25,125,Customer_125,ORD-23202,2025-02-09,comics,books,4,765.690,PayPal,Shipped,3062.76
26,126,Customer_126,ORD-11261,2025-05-18,shoes,clothing,4,836.800,Bank Transfer,Cancelled,3347.20
27,127,Customer_127,ORD-65482,2025-05-12,blender,home,5,336.020,Bank Transfer,Returned,1680.10
28,128,Customer_128,ORD-12270,2024-11-10,lamp,electronics,3,898.690,Bank Transfer,Delivered,2696.07
29,129,Customer_129,ORD-48863,2025-06-22,science,books,4,736.710,Bank Transfer,Returned,2946.84
30,130,Customer_130,ORD-34007,2025-08-15,tennis racket,sports,2,542.195,Bank Transfer,Processing,1084.39
31,131,Customer_131,ORD-91396,2025-06-11,lamp,home,5,616.630,PayPal,Shipped,3083.15
32,132,Customer_132,ORD-40186,2025-04-02,yoga mat,electronics,1,266.700,PayPal,Delivered,266.70
33,133,Customer_133,ORD-68182,2024-12-05,biography,books,5,343.240,Credit Card,Shipped,1716.20
34,134,Customer_134,ORD-16585,2025-10-04,t-shirt,clothing,3,591.530,PayPal,Shipped,1774.59
35,135,Customer_135,ORD-33656,2025-02-09,smartwatch,electronics,4,446.190,Cash on Delivery,Cancelled,1784.76
36,136,Customer_136,ORD-20985,2025-06-12,headphones,electronics,1,696.710,Credit Card,Delivered,696.71
37,137,Customer_137,ORD-91254,2025-02-23,vacuum,home,3,542.195,Cash on Delivery,Delivered,1626.58
38,138,Customer_138,ORD-34319,2025-08-09,lamp,home,1,531.060,PayPal,Processing,531.06
39,139,Customer_139,ORD-38418,2025-02-09,smartphone,electronics,2,681.380,Credit Card,Cancelled,1362.76
40,140,Customer_140,ORD-67096,2025-02-26,fiction,books,4,588.980,Credit Card,Returned,2355.92
41,141,Customer_141,ORD-45059,2025-02-13,fiction,books,3,546.040,Cash on Delivery,Returned,1638.12
42,142,Customer_142,ORD-69018,2025-10-30,shoes,clothing,5,645.260,Credit Card,Shipped,3226.30
43,143,Customer_143,ORD-14329,2025-07-11,t-shirt,clothing,5,826.770,Bank Transfer,Cancelled,4133.85
44,144,Customer_144,ORD-89452,2025-01-27,football,sports,5,849.070,Bank Transfer,Processing,4245.35
45,145,Customer_145,ORD-75314,2023-05-01,laptop,electronics,2,860.990,Bank Transfer,Returned,1721.98
46,146,Customer_146,ORD-32755,2025-07-09,basketball,electronics,2,705.420,Bank Transfer,Processing,1410.84
47,147,Customer_147,ORD-80707,2025-05-01,jacket,clothing,4,596.150,Cash on Delivery,Shipped,2384.60
48,148,Customer_148,ORD-38423,2025-03-13,tennis racket,sports,1,660.980,Cash on Delivery,Returned,660.98
49,149,Customer_149,ORD-95911,2025-06-29,comics,books,5,896.380,Bank Transfer,Cancelled,4481.90
50,150,Customer_150,ORD-76902,2024-11-27,yoga mat,sports,1,206.190,Credit Card,Returned,206.19
51,151,Customer_151,ORD-56552,2025-07-01,comics,books,2,457.160,PayPal,Processing,914.32
52,152,Customer_152,ORD-72869,2025-09-22,lamp,home,3,233.110,PayPal,Returned,699.33
53,153,Customer_153,ORD-29721,2025-07-16,yoga mat,sports,4,278.900,Cash on Delivery,Processing,1115.60
54,154,Customer_154,ORD-95990,2025-02-21,blender,home,5,789.640,Cash on Delivery,Cancelled,3948.20
55,155,Customer_155,ORD-20182,2025-05-01,shoes,clothing,1,40.950,PayPal,Returned,40.95
56,156,Customer_156,ORD-34679,2024-11-28,jeans,clothing,2,542.195,Bank Transfer,Shipped,1084.39
57,157,Customer_157,ORD-34407,2025-11-06,jacket,clothing,4,275.100,Bank Transfer,Processing,1100.40
58,158,Customer_158,ORD-35817,2025-04-05,smartwatch,electronics,1,933.580,Cash on Delivery,Shipped,933.58
59,159,Customer_159,ORD-98162,2025-07-28,microwave,home,3,163.160,PayPal,Shipped,489.48
60,160,Customer_160,ORD-96037,2025-01-03,science,books,5,242.520,Cash on Delivery,Returned,1212.60
61,161,Customer_161,ORD-27653,2024-12-15,science,books,4,209.320,Bank Transfer,Shipped,837.28
62,162,Customer_162,ORD-27743,2025-05-19,blender,home,2,155.760,Credit Card,Returned,311.52
63,163,Customer_163,ORD-24378,2023-01-05,smartwatch,electronics,3,235.260,Cash on Delivery,Shipped,705.78
64,164,Customer_164,ORD-23010,2025-02-09,tennis racket,sports,3,587.640,Credit Card,Returned,1762.92
65,165,Customer_165,ORD-55695,2024-11-08,shoes,clothing,2,443.130,Credit Card,Delivered,886.26
66,166,Customer_166,ORD-97756,2025-07-03,t-shirt,electronics,2,569.380,Cash on Delivery,Shipped,1138.76
67,167,Customer_167,ORD-30329,2025-08-07,basketball,sports,3,593.930,Cash on Delivery,Processing,1781.79
68,168,Customer_168,ORD-53430,2025-11-04,biography,books,2,141.490,PayPal,Cancelled,282.98
69,169,Customer_169,ORD-75539,2025-08-12,basketball,sports,1,582.130,Credit Card,Returned,582.13
70,170,Customer_170,ORD-21530,2025-10-03,jeans,clothing,5,741.630,Bank Transfer,Processing,3708.15
71,171,Customer_171,ORD-99790,2024-12-06,shoes,clothing,3,688.680,PayPal,Processing,2066.04
72,172,Customer_172,ORD-48008,2024-11-18,comics,books,2,942.760,Bank Transfer,Returned,1885.52
73,173,Customer_173,ORD-42171,2025-10-11,lamp,home,5,351.890,Credit Card,Shipped,1759.45
74,174,Customer_174,ORD-16766,2025-09-20,microwave,electronics,4,187.480,Credit Card,Returned,749.92
75,175,Customer_175,ORD-56651,2025-02-24,headphones,electronics,1,111.360,Credit Card,Processing,111.36
76,176,Customer_176,ORD-95794,2025-07-22,comics,books,5,530.520,Cash on Delivery,Shipped,2652.60
77,177,Customer_177,ORD-64136,2025-07-28,laptop,electronics,1,69.480,Bank Transfer,Returned,69.48
78,178,Customer_178,ORD-89906,2025-09-18,tennis racket,sports,3,472.140,PayPal,Returned,1416.42
79,179,Customer_179,ORD-99328,2025-09-03,yoga mat,sports,3,868.670,PayPal,Delivered,2606.01
80,180,Customer_180,ORD-86629,2025-03-26,laptop,electronics,2,418.380,Credit Card,Processing,836.76
81,181,Customer_181,ORD-54481,2024-12-29,smartphone,electronics,1,266.480,Cash on Delivery,Cancelled,266.48
82,182,Customer_182,ORD-79672,2025-08-03,shoes,clothing,4,538.350,PayPal,Processing,2153.40
83,183,Customer_183,ORD-20916,2025-03-10,shoes,clothing,5,542.195,Cash on Delivery,Returned,2710.97
84,184,Customer_184,ORD-67799,2025-02-15,jeans,NaN,4,101.190,Bank Transfer,Processing,404.76
85,185,Customer_185,ORD-57123,2025-08-14,football,sports,2,730.920,Cash on Delivery,Cancelled,1461.84
86,186,Customer_186,ORD-90569,2025-10-06,laptop,electronics,1,365.340,Bank Transfer,Delivered,365.34
87,187,Customer_187,ORD-41292,2024-11-19,smartphone,electronics,3,882.960,Bank Transfer,Returned,2648.88
88,188,Customer_188,ORD-58590,2024-11-19,microwave,home,5,504.050,Cash on Delivery,Shipped,2520.25
89,189,Customer_189,ORD-30627,2025-08-14,lamp,home,1,814.680,Cash on Delivery,Returned,814.68
90,190,Customer_190,ORD-38469,2025-06-29,vacuum,home,1,920.370,Bank Transfer,Processing,920.37
91,191,Customer_191,ORD-41810,2025-07-18,fiction,books,2,881.020,Cash on Delivery,Returned,1762.04
93,193,Customer_193,ORD-42475,2025-06-06,basketball,sports,3,522.020,PayPal,Shipped,1566.06
94,194,Customer_194,ORD-69764,2025-02-10,lamp,home,5,944.540,Cash on Delivery,Returned,4722.70
95,195,Customer_195,ORD-82876,2025-06-19,biography,books,5,817.460,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,2024-12-23,vacuum,home,3,542.195,PayPal,Delivered,1626.58
97,197,Customer_197,ORD-79139,2025-06-23,blender,home,1,160.160,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,2025-07-27,vacuum,home,2,497.010,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,2025-01-22,blender,home,5,372.280,Credit Card,Shipped,1861.40
100,175,Customer_175,NaN,2025-02-24,headphones,electronics,1,111.360,Credit Card,Processing,111.36
101,142,Customer_142,NaN,2025-10-30,shoes,clothing,5,645.260,Credit Card,Shipped,3226.30
102,146,Customer_146,NaN,2025-07-09,basketball,electronics,2,705.420,Bank Transfer,Processing,1410.84