In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv(r"C:\Users\AKSHAT\Desktop\E Commerce Project\messy_ecommerce_sales_data.csv")
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
...,...,...,...,...,...,...,...,...,...,...,...
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    object
 2   Order_ID        103 non-null    object
 3   Order_Date      103 non-null    object
 4   Product         103 non-null    object
 5    Category       95 non-null     object
 6   Quantity        98 non-null     object
 7   Price           98 non-null     object
 8   Payment_Method  103 non-null    object
 9   Status          103 non-null    object
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), object(9)
memory usage: 9.0+ KB

In [9]:
df.head()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51

In [10]:
df.describe()

               ID         Total
count  103.000000     89.000000
mean   149.640777   1232.949101
std     28.704326   2605.471455
min    100.000000 -20000.000000
25%    125.500000    582.130000
50%    149.000000   1138.760000
75%    174.500000   2153.400000
max    199.000000   4722.700000

In [9]:
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [13]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
5,105,Customer_105,ORD-22442,11/20/2024,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.180
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,Biography,Books,5,587.68,PayPal,Returned,2938.400
8,108,Customer_108,ORD-64400,10/23/2025,Science,Books,1,600.29,Cash on Delivery,Processing,600.290
9,109,Customer_109,ORD-18512,5/3/2025,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.700
10,110,Customer_110,ORD-61020,9/26/2025,Basketball,sports,5,four hundred,Cash on Delivery,Cancelled,NaN
11,111,Customer_111,ORD-72349,10/22/2025,Comics,Books,2,865.77,Credit Card,Returned,1731.540
12,112,Customer_112,ORD-80867,3/2/2025,Shoes,Clothing,4,752.13,Bank Transfer,Delivered,3008.520
13,113,Customer_113,ORD-23994,7/24/2025,Fiction,Books,1,411.81,Credit Card,Processing,411.810
14,114,Customer_114,ORD-77417,Jan 5 2023,Smartphone,Electronics,2,413.13,Cash on Delivery,Shipped,826.260
15,115,Customer_115,ORD-72778,1/10/2025,Fiction,Books,2,796.84,Cash on Delivery,Returned,1115.576
16,116,Customer_116,ORD-63660,10/30/2025,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,Blender,electronic,-2,10000,Cash on Delivery,Processing,-20000.000
18,118,Customer_118,ORD-96061,5/31/2025,Science,Books,5,247.82,PayPal,Processing,1239.100
19,119,Customer_119,ORD-76016,12/19/2024,Basketball,Sports,4,438.19,Cash on Delivery,Processing,1752.760
20,120,Customer_120,ORD-14659,6/13/2025,Yoga Mat,ELECTRONICS,5,300$,Credit Card,Cancelled,NaN
21,121,Customer_121,ORD-80067,10/11/2025,Basketball,Sports,4,523.01,Credit Card,Delivered,2092.040
22,122,Customer_122,ORD-21443,5/16/2025,Microwave,Home,2,556.93,PayPal,Shipped,1113.860
23,123,Customer_123,ORD-11314,10/6/2025,Vacuum,electronic,3,615.91,Cash on Delivery,Cancelled,1847.730
24,124,Customer_124,ORD-46136,5/31/2025,Comics,Books,5,NaN,PayPal,Cancelled,NaN
25,125,Customer_125,ORD-23202,2/9/2025,Comics,Books,4,765.69,PayPal,Shipped,3062.760
26,126,Customer_126,ORD-11261,5/18/2025,Shoes,Clothing,4,836.8,Bank Transfer,Cancelled,3347.200
27,127,Customer_127,ORD-65482,5/12/2025,Blender,Home,5,336.02,Bank Transfer,Returned,1680.100
28,128,Customer_128,ORD-12270,11/10/2024,Lamp,electronics,3,898.69,Bank Transfer,Delivered,2696.070
29,129,Customer_129,ORD-48863,6/22/2025,Science,Books,4,736.71,Bank Transfer,Returned,2946.840
30,130,Customer_130,ORD-34007,8/15/2025,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
31,131,Customer_131,ORD-91396,6/11/2025,Lamp,Home,5,616.63,PayPal,Shipped,3083.150
32,132,Customer_132,ORD-40186,4/2/2025,Yoga Mat,ELECTRONICS,1,266.7,PayPal,Delivered,266.700
33,133,Customer_133,ORD-68182,12/5/2024,Biography,NaN,5,343.24,Credit Card,Shipped,1716.200
34,134,Customer_134,ORD-16585,10/4/2025,T-shirt,Clothing,-5,591.53,PayPal,Shipped,-2957.650
35,135,Customer_135,ORD-33656,2/9/2025,Smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.760
36,136,Customer_136,ORD-20985,6/12/2025,Headphones,NaN,1,696.71,Credit Card,Delivered,696.710
37,137,Customer_137,ORD-91254,2/23/2025,Vacuum,Home,3,-100,Cash on Delivery,Delivered,-300.000
38,138,Customer_138,ORD-34319,8/9/2025,Lamp,Home,1,531.06,PayPal,Processing,531.060
39,139,Customer_139,ORD-38418,2/9/2025,Smartphone,Electronics,2,681.38,Credit Card,Cancelled,1362.760
40,140,Customer_140,ORD-67096,2/26/2025,Fiction,Books,4,588.98,Credit Card,Returned,2355.920
41,141,Customer_141,ORD-45059,2/13/2025,Fiction,Books,3,546.04,Cash on Delivery,Returned,1638.120
42,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,2258.410
43,143,Customer_143,ORD-14329,7/11/2025,T-shirt,Clothing,5,826.77,Bank Transfer,Cancelled,4133.850
44,144,Customer_144,ORD-89452,1/27/2025,Football,Sports,5,849.07,Bank Transfer,Processing,4245.350
45,145,Customer_145,ORD-75314,5/1/2023,Laptop,Electronics,2,860.99,Bank Transfer,Returned,1721.980
46,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840
47,147,Customer_147,ORD-80707,5/1/2025,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.600
48,148,Customer_148,ORD-38423,3/13/2025,Tennis Racket,Sports,1,660.98,Cash on Delivery,Returned,660.980
49,149,Customer_149,ORD-95911,6/29/2025,Comics,Books,5,896.38,Bank Transfer,Cancelled,4481.900
50,150,Customer_150,ORD-76902,11/27/2024,Yoga Mat,Sports,1,206.19,Credit Card,Returned,206.190
51,151,Customer_151,ORD-56552,7/1/2025,Comics,Books,2,457.16,PayPal,Processing,640.024
52,152,Customer_152,ORD-72869,9/22/2025,Lamp,Home,3,233.11,PayPal,Returned,699.330
53,153,Customer_153,ORD-29721,7/16/2025,Yoga Mat,Sports,4,278.9,Cash on Delivery,Processing,1115.600
54,154,Customer_154,ORD-95990,2/21/2025,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.200
55,155,Customer_155,ORD-20182,5/1/2025,shoes,Clothing,1,40.95,PayPal,Returned,40.950
56,156,Customer_156,ORD-34679,11/28/2024,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
57,157,Customer_157,ORD-34407,11/6/2025,Jacket,Clothing,4,275.1,Bank Transfer,Processing,1100.400
58,158,Customer_158,ORD-35817,4/5/2025,Smartwatch,Electronics,1,933.58,Cash on Delivery,Shipped,933.580
59,159,Customer_159,ORD-98162,7/28/2025,Microwave,Home,3,163.16,PayPal,Shipped,489.480
60,160,Customer_160,ORD-96037,1/3/2025,Science,Books,5,242.52,Cash on Delivery,Returned,1212.600
61,161,Customer_161,ORD-27653,12/15/2024,Science,Books,4,209.32,Bank Transfer,Shipped,837.280
62,162,Customer_162,ORD-27743,5/19/2025,Blender,Home,2,155.76,Credit Card,Returned,311.520
63,163,Customer_163,ORD-24378,1/5/2023,Smartwatch,Electronics,3,235.26,Cash on Delivery,Shipped,705.780
64,164,Customer_164,ORD-23010,2/9/2025,Tennis Racket,Sports,NaN,587.64,Credit Card,Returned,NaN
65,165,Customer_165,ORD-55695,11/8/2024,Shoes,Clothing,2,443.13,Credit Card,Delivered,886.260
66,166,Customer_166,ORD-97756,7/3/2025,T-shirt,electronics,2,569.38,Cash on Delivery,Shipped,1138.760
67,167,Customer_167,ORD-30329,8/7/2025,Basketball,Sports,NaN,593.93,Cash on Delivery,Processing,NaN
68,168,Customer_168,ORD-53430,11/4/2025,Biography,Books,2,141.49,PayPal,Cancelled,282.980
69,169,Customer_169,ORD-75539,8/12/2025,Basketball,Sports,1,582.13,Credit Card,Returned,582.130
70,170,Customer_170,ORD-21530,10/3/2025,Jeans,Clothing,5,741.63,Bank Transfer,Processing,3708.150
71,171,Customer_171,ORD-99790,12/6/2024,Shoes,Clothing,3,688.68,PayPal,Processing,2066.040
72,172,Customer_172,ORD-48008,11/18/2024,Comics,Books,2,942.76,Bank Transfer,Returned,1885.520
73,173,Customer_173,ORD-42171,10/11/2025,Lamp,Home,5,351.89,Credit Card,Shipped,1759.450
74,174,Customer_174,ORD-16766,9/20/2025,Microwave,ELECTRONICS,4,187.48,Credit Card,Returned,749.920
75,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,111.360
76,176,Customer_176,ORD-95794,7/22/2025,Comics,Books,5,530.52,Cash on Delivery,Shipped,2652.600
77,177,Customer_177,ORD-64136,7/28/2025,Laptop,Electronics,1,69.48,Bank Transfer,Returned,69.480
78,178,Customer_178,ORD-89906,9/18/2025,Tennis Racket,Sports,3,472.14,PayPal,Returned,1416.420
79,179,Customer_179,ORD-99328,9/3/2025,Yoga Mat,Sports,3,868.67,PayPal,Delivered,2606.010
80,180,Customer_180,ORD-86629,3/26/2025,Laptop,NaN,2,418.38,Credit Card,Processing,836.760
81,181,Customer_181,ORD-54481,12/29/2024,Smartphone,NaN,1,266.48,Cash on Delivery,Cancelled,266.480
82,182,Customer_182,ORD-79672,8/3/2025,Shoes,NaN,4,538.35,PayPal,Processing,2153.400
83,183,Customer_183,ORD-20916,3/10/2025,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN
84,184,Customer_184,ORD-67799,2/15/2025,Jeans,NaN,4,101.19,Bank Transfer,Processing,404.760
85,185,Customer_185,ORD-57123,8/14/2025,Football,Sports,2,730.92,Cash on Delivery,Cancelled,1023.288
86,186,Customer_186,ORD-90569,10/6/2025,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.340
87,187,Customer_187,ORD-41292,11/19/2024,Smartphone,Electronics,3,882.96,Bank Transfer,Returned,2648.880
88,188,Customer_188,ORD-58590,11/19/2024,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.250
89,189,Customer_189,ORD-30627,8/14/2025,Lamp,Home,1,814.68,Cash on Delivery,Returned,814.680
90,190,Customer_190,ORD-38469,6/29/2025,Vacuum,Home,1,920.37,Bank Transfer,Processing,920.370
91,191,Customer_191,ORD-41810,7/18/2025,Fiction,Books,2,881.02,Cash on Delivery,Returned,1762.040
92,192,Customer_192,ORD-35144,abc,Jacket,Clothing,4a,203.63,Credit Card,Returned,NaN
93,193,Customer_193,ORD-42475,6/6/2025,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
94,194,Customer_194,ORD-69764,2/10/2025,Lamp,Home,5,944.54,Cash on Delivery,Returned,4722.700
95,195,Customer_195,ORD-82876,6/19/2025,Biography,Books,5,817.46,Cash on Delivery,Returned,4087.300
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,Home,NaN,abd,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1,160.16,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [18]:
df.groupby('Price').mean(numeric_only = True)

                 ID      Total
Price
-100          137.0   -300.000
10000         117.0 -20000.000
101.19        184.0    404.760
111.36        175.0     94.656
122.06        105.0    366.180
141.49        168.0    282.980
155.76        162.0    311.520
160.16        197.0    160.160
163.16        159.0    489.480
168.34        109.0    841.700
187.48        174.0    749.920
203.63        192.0        NaN
206.19        150.0    206.190
209.32        161.0    837.280
233.11        152.0    699.330
233.92        103.0   1169.600
235.26        163.0    705.780
242.52        160.0   1212.600
247.82        118.0   1239.100
266.48        181.0    266.480
266.7         132.0    266.700
275.1         157.0   1100.400
278.9         153.0   1115.600
300$          120.0        NaN
336.02        127.0   1680.100
343.24        133.0   1716.200
351.89        173.0   1759.450
365.34        186.0    365.340
372.28        199.0   1861.400
38            100.0    114.000
389.05        102.0    389.050
40.95         155.0     40.950
411.81        113.0    411.810
413.13        114.0    826.260
418.38        180.0    836.760
438.19        119.0   1752.760
443.13        165.0    886.260
446.19        135.0   1784.760
457.16        151.0    640.024
472.14        178.0   1416.420
497.01        198.0    994.020
504.05        188.0   2520.250
522.02        193.0        NaN
523.01        121.0   2092.040
530.52        176.0   2652.600
531.06        138.0    531.060
538.35        182.0   2153.400
546.04        141.0   1638.120
552.51        104.0    552.510
556.93        122.0   1113.860
569.38        166.0   1138.760
582.13        169.0    582.130
587.64        164.0        NaN
587.68        107.0   2938.400
588.98        140.0   2355.920
591.53        134.0  -2957.650
593.93        167.0        NaN
596.15        147.0   2384.600
600.29        108.0    600.290
615.91        123.0   1847.730
616.63        131.0   3083.150
645.26        142.0   2742.355
660.98        148.0    660.980
681.38        139.0   1362.760
688.68        171.0   2066.040
69.48         177.0     69.480
696.71        136.0    696.710
705.42        146.0   1410.840
730.92        185.0   1023.288
736.71        129.0   2946.840
741.63        170.0   3708.150
752.13        112.0   3008.520
765.69        125.0   3062.760
789.64        154.0   3948.200
796.84        115.0   1115.576
814.68        189.0    814.680
817.46        195.0   4087.300
826.77        143.0   4133.850
836.8         126.0   3347.200
849.07        144.0   4245.350
860.99        145.0   1721.980
865.77        111.0   1731.540
868.67        179.0   2606.010
881.02        191.0   1762.040
882.96        187.0   2648.880
896.38        149.0   4481.900
898.69        128.0   2696.070
920.37        190.0    920.370
933.58        158.0    933.580
942.76        172.0   1885.520
944.54        194.0   4722.700
978.63        106.0        NaN
abd           148.5        NaN
four hundred  110.0        NaN

In [11]:
df.duplicated().sum()

np.int64(1)

In [12]:
df.nunique()

ID                100
 Customer_Name    100
Order_ID          100
Order_Date         86
Product            21
 Category           9
Quantity            8
Price              94
Payment_Method      4
Status              5
Total              88
dtype: int64